version: "3.8"

services:
  bot:
    build: ./bot
    volumes:
      - ./bot:/usr/src/bot:rw
    env_file:
      - .env
    environment:
      # bot token
      - TOKEN=${TOKEN}
      # TimeZone
      - TZ=Asia/Tokyo
    tty: true
    command: [ "python3", "main.py" ]
    restart: always
    ports:
      - '3000:${PORT}'
    networks:
      - default
